version: '3'
services:
  postgresql:
    image: postgres
    container_name: database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=database
      - POSTGRES_DATABASE=database
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-database
    ports:
      - '6379-6379'